version: '2'
services:
  jhmybatis-app:
    image: jhmybatis
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://jhmybatis-mariadb:3306/jhmybatis
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  jhmybatis-mariadb:
    extends:
      file: mariadb.yml
      service: jhmybatis-mariadb
